//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public int Id { get; set; }
        public string Id_Asiento { get; set; }
        public string Descripcion { get; set; }
        public int Cliente_ID { get; set; }
        public string Cuenta { get; set; }
        public string Tipo_movimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Monto { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
