//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccione
    {
        public int Id { get; set; }
        public string Id_transaccion { get; set; }
        public string Tipo_Mov { get; set; }
        public int TipoDoc_ID { get; set; }
        public string Num_doc { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cliente_ID { get; set; }
        public int Monto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Tipos_Documentos Tipos_Documentos { get; set; }
    }
}
